Fix bug in log.py
deepmodeling/dpdata pull request #116
Opened 2020-10-09 02:51 UTC by trollchu

For system with more than 50 atoms, gaussian will not output the " Input orientation" or "Z-Matrix orientation", so we need to add keywords "Standard orientation". Instead, you can add "geom=printinputorient" keywords in the gaussian input to get the " Input orientation".

2020-10-09 09:13 UTC, njzjz requested changes
The standard orientation is different from the input orientation, see https://gaussian.com/symmetry/. Use the standard orientation will cause inconsistent with coordinates and forces.

2020-10-09 12:08 UTC, trollchu commented
> The standard orientation is different from the input orientation, see https://gaussian.com/symmetry/. Using the standard orientation will cause inconsistent with coordinates and forces.

Do you mean that the atom index in the force output is the same as the input orientation， but maybe not be the same as standard orientation？

2020-10-09 13:32 UTC, njzjz commented
> > The standard orientation is different from the input orientation, see https://gaussian.com/symmetry/. Using the standard orientation will cause inconsistent with coordinates and forces.
> 
> 
> 
> Do you mean that the atom index in the force output is the same as the input orientation， but maybe not be the same as standard orientation？ 

The coordinates may be rotated, but the force output will not.

2020-10-09 13:40 UTC, trollchu commented
> > > The standard orientation is different from the input orientation, see https://gaussian.com/symmetry/. Using the standard orientation will cause inconsistent with coordinates and forces.
> > 
> > 
> > Do you mean that the atom index in the force output is the same as the input orientation， but maybe not be the same as standard orientation？
> 
> The coordinates may be rotated, but the force output will not.

get it，thanks :)

2020-10-09 13:40 UTC, closed without merging

2023-07-28 02:35 UTC, Zhang-Zhiyuan-zzy commented
In certain situations, it is possible that we may only require the molecular conformer without the need to align the atoms' coordinate orientation with their force vectors. In my particular case, all I need is the molecular conformers and the corresponding energies. Would it be feasible to incorporate a non-default flag to allow for this less stringent operation?