if cp2k output is not converged, return the sys len = 0
deepmodeling/dpdata pull request #184
Opened 2021-08-03 11:36 UTC by robinzyb

2021-08-03 19:00 UTC, njzjz commented on dpdata/cp2k/output.py
> +    fp = open(fname)
Instead of opening fname twice, I prefer using `fp.seek(0)`.

2021-08-04 06:57 UTC, robinzyb commented on tests/cp2k/cp2k_output
> + *** SCF run converged in    47 steps ***
this file is only used to check the content from parser. add `run converged` to parse by dpdata.

2021-08-05 02:23 UTC, njzjz requested changes
Can you add a test for non-coverage system like this one
https://github.com/deepmodeling/dpdata/blob/73ad1640e7511f2c2d2df8f842e529f86945168e/tests/test_gaussian_log.py#L51-L75

2021-08-09 02:44 UTC, njzjz approved these changes

2021-08-09 03:09 UTC, merged