add MultiSystem for ASE traj(or any other format can be read by ASE)
deepmodeling/dpdata pull request #190
Opened 2021-08-27 10:20 UTC by bigd4

add MultiSystem for ASE traj(or any other format can be read by ASE)
fix bug(?) for ASE 'to_labeled_system'

2021-08-30 03:48 UTC, njzjz requested changes
Please set the target branch to `devel` instead of `master` (you can click the `edit` button).

2021-08-30 03:48 UTC, njzjz commented on dpdata/plugins/ase.py
> +    raise Exception('ASE module not installed')
This line should be removed, as `ase` is only an optional package.

2021-08-30 03:48 UTC, njzjz commented on dpdata/plugins/ase.py
> +except:
[Do not use base `except:` clause.](https://www.python.org/dev/peps/pep-0008/#programming-recommendations)

2021-08-30 03:48 UTC, njzjz commented on dpdata/plugins/ase.py
> +            except:
Do not use base `except:` clause.

2021-08-30 03:48 UTC, njzjz commented on dpdata/plugins/ase.py
> +    def from_multi_systems(self, file_name, begin=None, end=None, step=None, fmt='traj', **kwargs):
Please consider add unit tests for this new method.

2021-08-30 18:32 UTC, njzjz approved these changes

2021-08-31 02:20 UTC, amcadmus approved these changes

2021-08-31 02:22 UTC, merged