Fix 296
deepmodeling/dpdata pull request #297
Opened 2022-05-26 13:14 UTC by amcadmus

2022-05-26 15:23 UTC, njzjz approved these changes

2022-05-26 23:11 UTC, njzjz requested changes

2022-05-26 23:11 UTC, njzjz commented on dpdata/qe/traj.py
> +        return bohr
```suggestion
        return 'bohr'
```

2022-05-26 23:12 UTC, njzjz commented on dpdata/qe/traj.py
> +        return bohr
An obvious typo here. Is this line covered?

2022-05-27 00:54 UTC, wanghan-iapcm commented
No the UT should have covered all cases. @njzjz

2022-05-27 02:01 UTC, njzjz approved these changes

2022-06-11 09:43 UTC, closed without merging