Add support for 'deepmd/mixed' format with dpdata.MultiSystems
deepmodeling/dpdata pull request #422
Opened 2023-02-19 16:01 UTC by iProzd

Add support for 'deepmd/mixed' format with dpdata.MultiSystems
1. Support dump from dpdata.MultiSystems to [mixed type format](https://github.com/deepmodeling/deepmd-kit/blob/master/doc/model/train-se-atten.md#data-format):
    dpdata.MultiSystems.to_deepmd_mixed('dir_name_mixed')
2. Support load from mixed type format to dpdata.MultiSystems:
    dpdata.MultiSystems.load_systems_from_file('dir_name_mixed', fmt='deepmd/mixed')

2023-02-19 16:02 UTC, iProzd commented
I've add unittest for this, but I'm wondering where to add the docs.

2023-02-19 16:05 UTC, iProzd commented
@wanghan-iapcm @njzjz

2023-02-19 16:14 UTC, njzjz commented
The docs can be automatically generated in https://deepmodeling--422.org.readthedocs.build/projects/dpdata/en/422/formats.html

2023-02-19 21:23 UTC, njzjz commented on dpdata/plugins/deepmd.py
> +@Format.register("deepmd/mixed")
I think it's actually `deepmd/npy/mixed`. We can also have `deepmd/raw/mixed` and `deepmd/hdf5/mixed`.

2023-02-19 21:23 UTC, njzjz commented on dpdata/plugins/deepmd.py
> +    def to_system(self, data, file_name, set_size=200, prec=np.float64, **kwargs):
Is there any reason to set the default of set size to 200? If only one set is supported, I think we should remove this option.

2023-02-19 21:23 UTC, njzjz commented on dpdata/plugins/deepmd.py
> +        file_name : str
This doc doesn't match the actual parameters.

2023-02-19 21:23 UTC, njzjz commented on dpdata/system.py
> +        self.data["atom_types"] = np.array([0 for i in range(natoms)])
`np.zeros((natoms,), dtype=int)`

2023-02-20 00:45 UTC, wanghan-iapcm requested changes
I find the UT is trivial: All systems has the same types and numbers of atoms. Please provide tests for the cases 
- systems has the same total number of atoms but different atom types, 
- systems has different total numbers of atoms,

and  see if your code is working as it was designed. 

The doc for the mix type is also missing. Please provide the doc.

2023-02-22 01:08 UTC, njzjz requested changes

2023-02-22 01:08 UTC, njzjz commented on dpdata/plugins/deepmd.py
> +class DeePMDMixedFormat(Format):
Could you add documentation here for this format?
(I am not sure what is the best way to do it, but we should have an automatic way to have documentation for so many different formats)

2023-02-22 22:58 UTC, njzjz approved these changes

2023-02-23 02:37 UTC, wanghan-iapcm approved these changes

2023-02-23 02:40 UTC, merged