fix #359: read atom names from POTCAR if not present in OUTCAR
deepmodeling/dpdata pull request #443
Opened 2023-03-30 09:18 UTC by hoba87

2023-03-31 03:31 UTC, wanghan-iapcm requested changes

2023-03-31 03:31 UTC, wanghan-iapcm commented on dpdata/vasp/outcar.py
> +        elif "POTCAR" in ii:
my outcar reads
```
 INCAR:
 POTCAR:    PAW_PBE Mg 13Apr2007                  
 POTCAR:    PAW_PBE Mg 13Apr2007                  
   VRHFIN =Mg: s2p0                                                             
   LEXCH  = PE                                                                  
   EATOM  =    23.0369 eV,    1.6932 Ry                                         
                                                                                
   TITEL  = PAW_PBE Mg 13Apr2007                                                
   LULTRA =        F    use ultrasoft PP ?                                      
   IUNSCR =        1    unscreen: 0-lin 1-nonlin 2-no                           
```

Then the same atom name will be added three times.

2023-04-03 00:58 UTC, wanghan-iapcm requested changes

2023-04-03 00:58 UTC, wanghan-iapcm commented on dpdata/vasp/outcar.py
> +        elif "POTCAR" in ii:
The dpdata is expected to abstract atom names in an order that is exact the same as how the potcars are concatenated. 
Your implementation does not work for the cases like "A" "B" "A" "B"

2023-04-13 12:18 UTC, hoba87 commented
Why does it not work for "A" "B" "A" "B", just skipping the second "A" "B"?

2023-04-17 00:45 UTC, wanghan-iapcm commented
> Why does it not work for "A" "B" "A" "B", just skipping the second "A" "B"?

The expected atom names is "A" "B" "A" "B". Your PR changes the behavior of dpdata.

2023-04-17 11:33 UTC, hoba87 commented
Ok, do I understand you right, there exist cases with different pseudopotentials for the same atom type? If that is the case, I have no idea how to cover that.
Then I will keep my changes seperatly and you can close the pull request.

2023-04-19 12:41 UTC, wanghan-iapcm commented
> Ok, do I understand you right, there exist cases with different pseudopotentials for the same atom type? If that is the case, I have no idea how to cover that. Then I will keep my changes seperatly and you can close the pull request.

The same pseudopotential file for difference sections of atoms. One is allowed to generate POTCAR by e.g.
```
cat POTCAR_A POTCAR_B POTCAR_A POTCAR_B > POTCAR
```
and write four sections of atoms having types A B A B in POSCAR.

2026-08-19 15:16 UTC, njzjz commented
Thanks for the contribution. I recommend closing this PR because the underlying requirement has already been addressed by a newer implementation.

The fallback for reading atom names when they are missing from `OUTCAR` was subsequently implemented in #844 / `bb14c5a`, with safer handling of repeated POTCAR information and dedicated tests. The deduplication approach in this older branch is not structurally safe, and the branch now also conflicts with `master`.

Rather than rebasing this implementation, it would be better to keep the newer tested implementation as the canonical solution.

Agent: ChatGPT
Model: GPT-5.6 Sol

2026-08-19 15:16 UTC, closed without merging