new feature DFTB+
deepmodeling/dpdata pull request #511
Opened 2023-07-26 08:51 UTC by ruio248

2023-07-26 19:28 UTC, njzjz requested changes

2023-07-26 19:28 UTC, njzjz commented on dpdata/dftb_plus/inout.py
> +    forces = -np.array(forces)
It seems that DFTB+ outputs forces instead of gradients, so forces should not multiply by -1.

(need check)

2023-07-26 19:28 UTC, njzjz commented on dpdata/dftb_plus/inout.py
> +def read_dftb_plus(fn: str) -> Tuple[str, np.ndarray, float, np.ndarray]:
DFTB+ has input and output files separately, so I suggest not merging them into one file. Instead, pass a directory or two file arguments.

2023-07-27 01:48 UTC, wanghan-iapcm reviewed
Please provide doc for this format.

2023-07-31 04:25 UTC, njzjz commented on tests/dftb_plus/dftb_pin.hsd
> +}
From dftb+ documentation

> The second line contains the chemical symbols of the elements present separated by one or more spaces. The following n lines contain a list of the atoms. The first number is the atom number in the structure (this is currently ignored by the program). The second number is the chemical type from the list of symbols on line 2. Then follow the coordinates. For S and C format, these are x, y, z in Å, but for F they are fractions of the three lattice vectors.

So the unit is Angstrom

2023-07-31 11:39 UTC, ruio248 commented
> Please provide doc for this format.
The doc is provided in dpdata/plugins/dftbplus.py

2023-07-31 18:31 UTC, njzjz approved these changes

2023-08-01 08:29 UTC, wanghan-iapcm reviewed
Please update dftb+ format to readme:

2023-08-05 07:29 UTC, merged