fix cp2k 2023 output
deepmodeling/dpdata pull request #533
Opened 2023-09-04 07:56 UTC by link89

fix https://github.com/deepmodeling/dpdata/issues/508

2023-09-04 16:13 UTC, njzjz requested changes
Please resolve conflicts.

2023-09-04 16:25 UTC, link89 commented
Fix conflict and refactor the implementation on devel branch

2023-09-05 09:06 UTC, robinzyb approved these changes

2023-09-05 18:09 UTC, njzjz approved these changes

2023-09-06 01:13 UTC, merged