add decrecaption warning when dpdata throws errors while parsing cp2k
deepmodeling/dpdata pull request #558
Opened 2023-10-20 22:52 UTC by robinzyb

2023-10-21 00:04 UTC, njzjz commented
#556 didn't throw any errors though

2023-10-23 10:10 UTC, robinzyb commented
> #556 didn't throw any errors though

I don't know how he wrote the code for dpdata, however, I got errors when I use his files.
```python
import dpdata
dpdata.LabeledSystem(file_name="./55-20rfj2", fmt="cp2k/aimd_output")
```

```shell
{
	"name": "PendingDeprecationWarning",
	"message": "
Hi, you got an error from dpdata, 
please check if your cp2k files include full information,
otherwise its version is not supported by dpdata.
Try use dpdata plugin from cp2kdata package,
for details, please refer to
https://robinzyb.github.io/cp2kdata/
",
	"stack": "---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~/anaconda3/envs/ectoolkit/lib/python3.8/site-packages/dpdata/plugins/cp2k.py:22, in CP2KAIMDOutputFormat.from_labeled_system(self, file_name, restart, **kwargs)
     21 xyz_file = sorted(glob.glob(f\"{file_name}/*pos*.xyz\"))[0]
---> 22 log_file = sorted(glob.glob(f\"{file_name}/*.log\"))[0]
     23 print(tuple(Cp2kSystems(log_file, xyz_file, restart)))

IndexError: list index out of range

During handling of the above exception, another exception occurred:

PendingDeprecationWarning                 Traceback (most recent call last)
/Users/robinzhuang/workdir/tmp/cp2kdata_testspace/Untitled-1.ipynb Cell 2 line 2
      <a href='vscode-notebook-cell:/Users/robinzhuang/workdir/tmp/cp2kdata_testspace/Untitled-1.ipynb#W1sZmlsZQ%3D%3D?line=0'>1</a> import dpdata
----> <a href='vscode-notebook-cell:/Users/robinzhuang/workdir/tmp/cp2kdata_testspace/Untitled-1.ipynb#W1sZmlsZQ%3D%3D?line=1'>2</a> dpdata.LabeledSystem(file_name=\"./55-20rfj2\", fmt=\"cp2k/aimd_output\")

File ~/anaconda3/envs/ectoolkit/lib/python3.8/site-packages/dpdata/system.py:281, in System.__init__(self, file_name, fmt, type_map, begin, step, data, convergence_check, **kwargs)
    279 if file_name is None:
    280     return
--> 281 self.from_fmt(
    282     file_name,
    283     fmt,
    284     type_map=type_map,
    285     begin=begin,
    286     step=step,
    287     convergence_check=convergence_check,
    288     **kwargs,
    289 )
    291 if type_map is not None:
    292     self.apply_type_map(type_map)

File ~/anaconda3/envs/ectoolkit/lib/python3.8/site-packages/dpdata/system.py:318, in System.from_fmt(self, file_name, fmt, **kwargs)
    316 if fmt == \"auto\":
    317     fmt = os.path.basename(file_name).split(\".\")[-1].lower()
--> 318 return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)

File ~/anaconda3/envs/ectoolkit/lib/python3.8/site-packages/dpdata/system.py:1162, in LabeledSystem.from_fmt_obj(self, fmtobj, file_name, **kwargs)
   1161 def from_fmt_obj(self, fmtobj, file_name, **kwargs):
-> 1162     data = fmtobj.from_labeled_system(file_name, **kwargs)
   1163     if data:
   1164         if isinstance(data, (list, tuple)):

File ~/anaconda3/envs/ectoolkit/lib/python3.8/site-packages/dpdata/plugins/cp2k.py:27, in CP2KAIMDOutputFormat.from_labeled_system(self, file_name, restart, **kwargs)
     25     return tuple(Cp2kSystems(log_file, xyz_file, restart))
     26 except :
---> 27     raise PendingDeprecationWarning(string_warning)

PendingDeprecationWarning: 
Hi, you got an error from dpdata, 
please check if your cp2k files include full information,
otherwise its version is not supported by dpdata.
Try use dpdata plugin from cp2kdata package,
for details, please refer to
https://robinzyb.github.io/cp2kdata/
"
}
```

2023-10-25 17:47 UTC, njzjz commented
Firstly, move `1.out` to `1.log` as `*.log` is hard-coded in the code. (There should be an argument to adjust it.)

```sh
mv 1.out 1.log
```

Then there are no errors anymore. Catching an exception will not work.

```py
>>> import dpdata
>>> dpdata.LabeledSystem(file_name="./", fmt="cp2k/aimd_output")
Data Summary
Labeled System
-------------------
Frame Numbers      : 0
Atom Numbers       : 0
Including Virials  : No
Element List       :
-------------------
```

2023-10-30 19:54 UTC, robinzyb commented
The old code returns empty dict even if nothing is matched. Extra lines are added to raise StopIteration when all matches is failed.

2023-10-30 20:06 UTC, njzjz commented on dpdata/plugins/cp2k.py
> +            print(string_warning)
This ignores the error and does not exit the program. Is it expected?

2023-10-30 20:19 UTC, njzjz commented on dpdata/plugins/cp2k.py
> +            print(string_warning)
There may be two codes acceptable:

```py
except RuntimeError from e:
    raise PendingDeprecationWarning(string_warning) from e
```

or 

```py
except RuntimeError from e:
    warnings.warn(string_warning)
    raise e
```

2023-10-30 20:20 UTC, njzjz requested changes

2023-10-30 20:20 UTC, njzjz commented on dpdata/plugins/cp2k.py
> +            log_file = sorted(glob.glob(f"{file_name}/*.log"))[0]
These two lines do not need to be inside the `try...except` block.

2023-10-30 20:59 UTC, njzjz approved these changes
LGTM. Just a grammar issue.

2023-10-30 20:59 UTC, njzjz commented on dpdata/plugins/cp2k.py
> +Try use dpdata plugin from cp2kdata package,
```suggestion
Try to use dpdata plugin from cp2kdata package,
```

2023-10-30 21:02 UTC, merged

2023-10-30 21:09 UTC, njzjz commented
@robinzyb, we only use Squash merge.

2023-10-30 21:21 UTC, njzjz commented
I squashed and recommitted this PR in 7fb45d88452886572edba7f48269c79fb84fb22e and force-pushed to the devel branch.

2023-10-31 11:19 UTC, robinzyb commented
> @robinzyb, we only use Squash merge.

sorry. didn't know the procedure. How should I do next?

2023-10-31 18:56 UTC, njzjz commented
> How should I do next?

Nothing, as I've manually resolved it. But next time, you'd better select "squash and merge".

![image](https://github.com/deepmodeling/dpdata/assets/9496702/88ca25d1-f940-41b5-981a-6d6d549fb2c2)