Add support for converting move flags between Abacus and VASP
deepmodeling/dpdata pull request #744
Opened 2024-10-26 06:24 UTC by Angel-Jia

2024-10-26 06:27 UTC, Angel-Jia commented
Currently, only input files POSCAR for VASP and STRU for Abacus are supported. The move flags in their output files have not been handled yet.

2024-10-28 04:00 UTC, wanghan-iapcm requested changes
The newly defined data type `"move"` should be registered. for example 
https://github.com/deepmodeling/dpdata/blob/7853b7b526a5ffbd2b8a08d3a1f3ffa06c228d52/dpdata/plugins/abacus.py#L49

otherwise, it will not handled by dpdata, which may be tested by load and dump the same poscar file.

2024-10-29 03:51 UTC, wanghan-iapcm requested changes

2024-10-29 03:51 UTC, wanghan-iapcm commented on dpdata/plugins/abacus.py
> +        dpdata.System.register_data_type(dt)
not a good idea to register "move" in the function `register_mag_data`, which registers the magnatic related variable and labels.

2024-10-29 04:01 UTC, wanghan-iapcm approved these changes

2024-10-29 05:53 UTC, merged